version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: github_oauth_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      GITHUB_CLIENT_ID: "${SGITHUB_CLIENT_ID}"
      GITHUB_CLIENT_SECRET: "${SGITHUB_CLIENT_SECRET}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      FRONTEND_URL: "${FRONTEND_URL}"
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
       - ./frontend:/app:delegated
       - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: /api

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: rajesh@pestrust.edu.in
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PREFIX: "'/'" 
      PGADMIN_CONFIG_APP_NAME: "'pgAdmin'"
      PGADMIN_CONFIG_LOGIN_BANNER:  "'Welcome to pgAdmin on Codespaces'"
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data:
